### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by roedie** [mrlesmithjr/ansible-config-interfaces#1]
Hi, would it be an idea to modify the defaults so it doesn't config all those interfaces?

It makes it kind of a hassle to manage since by default it configures a *lot* of interfaces.

I don't mind creating a pull for it.

Regards,

Sander

**Comment by mrlesmithjr** [comment]
Not a bad idea at all. I can work on this.

**Comment by mrlesmithjr** [comment]
@roedie I have updated the defaults and also added some additional functionality. I have been meaning to get back to this role for other reasons, so thanks for this poke!
