### ISSUE TITLE
Allow overriding package install

### ISSUE THREAD

**Issue by jdeluyck** [mrlesmithjr/ansible-config-interfaces#25]
**Is your feature request related to a problem? Please describe.**
I'm using your role to configure interfaces on a proxmox (debian based) host. When configuring vlan interfaces, the role attempts to install the package vlan, which conflicts with parts of the proxmox installation.

Right now I have a block on the package using an apt preferences file, but it'd be nice if i could specify a flag not to install the packages.

**Describe the solution you'd like**
A flag to not install packages

```
$ sudo cat block_vlans 
Package: vlan
Pin: release *
Pin-Priority: -1

$ sudo apt install vlan
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'pve-manager' instead of 'vlan'
pve-manager is already the newest version (6.4-8).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by Andre15711** [comment]
Even if is closed, it is sill an issue.
I have the same conflict.

Any solution for this?

**Comment by jdeluyck** [comment]
I'm fairly sure this has been abandoned (3y no updates), so I went another way.

**Comment by mrlesmithjr** [comment]
I haven't used this role in quite a while, and I think most have potentially switched to https://github.com/mrlesmithjr/ansible-netplan. However, if there is a need for this role to exist still and be updated, please feel free to open a PR, as they are more than welcome.

**Comment by Andre15711** [comment]
> I'm fairly sure this has been abandoned (3y no updates), so I went another way.

Which way? Did Zoe found an other role that is working with proxmox-ve?

**Comment by Andre15711** [comment]
> I haven't used this role in quite a while, and I think most have potentially switched to https://github.com/mrlesmithjr/ansible-netplan. However, if there is a need for this role to exist still and be updated, please feel free to open a PR, as they are more than welcome.


I tried this one. The output format is very different and pro mix will not apply this net config.
