### ISSUE TITLE
Role uses ansible.builtin.include which has been removed with Ansible 2.16

### ISSUE THREAD

**Issue by balaji-dutt** [mrlesmithjr/ansible-config-interfaces#27]
**Describe the bug**
The role's main.yml uses `include` which has been [removed with Ansible 2.16](https://docs.ansible.com/ansible-core/2.12/collections/ansible/builtin/include_module.html#deprecated)

**To Reproduce**
1. Install Ansible 2.16 or greater
2. Create an ansible playbook that uses the role
3. Run playbook
4. See error as shown below:
```
ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.
```

**Expected behavior**
The playbook should use `include_tasks` or `import_tasks` instead so it can be used with Ansible 2.16 or greater.

**Comment by mrlesmithjr** [comment]
@balaji-dutt Feel free to submit a PR for this
